# Generated by Django 4.2.4 on 2023-09-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_alter_orders_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ty',
            new_name='qty',
        ),
    ]
